name: Run Selenium Tests Nightly

on:
  schedule:
    - cron: '0 5 * * *' # Runs at 10 PM PST time every night (5 AM UTC)
  workflow_dispatch:    # Runs manually
    inputs:
      tests:
        description: 'Choose which tests to run'
        required: true
        default: 'print_differences'
        type: choice
        options:
          - all
          - print_differences

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install pipenv
      run: python3 -m pip install --upgrade pip && pip install pipenv

    - name: Install dependencies using Pipfile
      run: pipenv install

    - name: Run tests using pytest
      run: |
        if [ "${{ github.event.inputs.tests }}" == "print_differences" ]; then
          pipenv run python -m pytest -m print_differences --verbose --html=reports/report.html --self-contained-html -s;
        else
          pipenv run python -m pytest --verbose --html=reports/report.html --self-contained-html -s;
        fi

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-report
        path: reports/report.html
